name: Daily Load to GCP

on:
  schedule:
    - cron: '0 2 * * *'  # Runs every day at 2 AM UTC
  workflow_dispatch:     # Allows manual triggering from GitHub Actions UI

jobs:
  load-data:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install requests google-cloud-storage google-cloud-bigquery

      - name: Authenticate to GCP
        run: |
          # Decode the base64 secret into sa.json
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > sa.json
          head -n 5 sa.json  # Debug: Verify that sa.json is valid (remove this in production)
      
          # Set the environment variable so Python can find credentials
          echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/sa.json" >> $GITHUB_ENV
      
          # Authenticate using gcloud
          gcloud auth activate-service-account --key-file=sa.json
          gcloud config set project ae-class-project

      - name: Run the Python script
        run: python scripts/pull_and_upload_csvs.py

      - name: Load GCS data into BigQuery
        run: python scripts/load_gcs_to_bq.py
